typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)

typeset -g POWERLEVEL9K_MODE='nerdfont-complete'

typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PREFIX_START='%#'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PREFIX_END='%f'

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=0
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=0
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=0

typeset -g POWERLEVEL9K_DIR_FOREGROUND=0
typeset -g POWERLEVEL9K_DIR_BACKGROUND=4

typeset -g POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_last"
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=""

typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1

typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{7}\uE0B1%f'
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%F{7}\uE0B3%f'

typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=0
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=0
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=0

typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_MODIFIED_ICON='✚'
typeset -g POWERLEVEL9K_VCS_STAGED_ICON='●'

typeset -g POWERLEVEL9K_VCS_FORMAT_BRANCH='%b'
